# Intent 정의
# 사용자의 의도를 분류하기 위한 설정 파일
#
# 이 파일을 수정하여 도메인별 Intent를 정의할 수 있습니다.
# 부동산 챗봇에서 범용 프레임워크로 전환하면서 범용 Intent로 변경되었습니다.

# Intent 목록
intents:
  # ============================================================================
  # 범용 Intent (기본 제공)
  # ============================================================================

  - name: "information_inquiry"
    display_name: "정보 조회"
    description: "데이터 검색 및 조회 요청"
    keywords:
      - "조회"
      - "검색"
      - "찾기"
      - "알려주"
      - "보여주"
      - "what"
      - "where"
      - "which"
      - "who"
    confidence_threshold: 0.6
    suggested_agents:
      - "search_team"
    priority: 1
    examples:
      - "데이터 조회해줘"
      - "정보 찾아줘"
      - "어디 있어?"

  - name: "data_analysis"
    display_name: "데이터 분석"
    description: "데이터 분석 및 인사이트 도출"
    keywords:
      - "분석"
      - "평가"
      - "비교"
      - "추천"
      - "analyze"
      - "compare"
      - "recommend"
      - "어때"
      - "좋아"
    confidence_threshold: 0.7
    suggested_agents:
      - "search_team"
      - "analysis_team"
    priority: 2
    examples:
      - "분석해줘"
      - "비교해줘"
      - "추천해줘"

  - name: "document_generation"
    display_name: "문서 생성"
    description: "문서 작성 및 생성 요청"
    keywords:
      - "작성"
      - "생성"
      - "만들기"
      - "만들어"
      - "create"
      - "generate"
      - "write"
    confidence_threshold: 0.7
    suggested_agents:
      - "document_team"
    priority: 2
    examples:
      - "문서 작성해줘"
      - "만들어줘"
      - "생성해줘"

  - name: "document_review"
    display_name: "문서 검토"
    description: "문서 검토 및 분석 요청"
    keywords:
      - "검토"
      - "리뷰"
      - "확인"
      - "review"
      - "check"
      - "verify"
    confidence_threshold: 0.7
    suggested_agents:
      - "document_team"
      - "analysis_team"
    priority: 2
    examples:
      - "검토해줘"
      - "확인해줘"
      - "리뷰해줘"

  - name: "comprehensive_analysis"
    display_name: "종합 분석"
    description: "다양한 측면에서의 종합적인 분석"
    keywords:
      - "종합"
      - "전체"
      - "모든"
      - "자세히"
      - "comprehensive"
      - "overall"
      - "detailed"
    confidence_threshold: 0.75
    suggested_agents:
      - "search_team"
      - "analysis_team"
      - "document_team"
    priority: 3
    examples:
      - "전체적으로 분석해줘"
      - "자세히 알려줘"
      - "종합적으로 검토해줘"

  # ============================================================================
  # 특수 Intent (시스템)
  # ============================================================================

  - name: "unclear"
    display_name: "불명확"
    description: "사용자 의도를 파악할 수 없는 경우"
    keywords: []
    confidence_threshold: 0.0
    suggested_agents: []
    priority: 99
    system: true
    response_template: |
      죄송합니다. 질문의 의도를 정확히 파악하지 못했습니다.

      좀 더 구체적으로 질문해 주시겠어요?
      예를 들어:
      - "데이터 조회해줘"
      - "분석해줘"
      - "문서 작성해줘"

  - name: "irrelevant"
    display_name: "범위 외"
    description: "서비스 범위를 벗어난 질문"
    keywords:
      - "날씨"
      - "시간"
      - "농담"
      - "게임"
    confidence_threshold: 0.0
    suggested_agents: []
    priority: 99
    system: true
    response_template: |
      죄송합니다. 해당 질문은 제 서비스 범위를 벗어납니다.

      저는 다음과 같은 도움을 드릴 수 있습니다:
      - 정보 조회 및 검색
      - 데이터 분석 및 비교
      - 문서 생성 및 검토

# Intent 매칭 설정
matching:
  # 최소 신뢰도 (이 값 미만이면 unclear로 분류)
  min_confidence: 0.5

  # Fallback intent (의도 파악 실패 시)
  fallback_intent: "unclear"

  # LLM 기반 분류 사용 여부
  use_llm_classification: true

  # LLM 모델 (framework.yaml의 intent_analysis 모델 사용)
  llm_model: "gpt-4o-mini"

  # 키워드 가중치 (LLM과 키워드 매칭 결합 시)
  keyword_weight: 0.3
  llm_weight: 0.7

# 도메인별 커스터마이징 가이드
#
# 1. 새로운 Intent 추가:
#    - name: 고유 식별자 (영문, 소문자, 언더스코어)
#    - display_name: 화면 표시 이름
#    - description: Intent 설명
#    - keywords: 관련 키워드 리스트
#    - confidence_threshold: 신뢰도 임계값
#    - suggested_agents: 실행할 Agent 팀 리스트
#    - priority: 우선순위 (낮을수록 우선)
#
# 2. 기존 Intent 수정:
#    - keywords에 도메인별 키워드 추가
#    - suggested_agents에 커스텀 Agent 추가
#
# 3. Intent 비활성화:
#    - enabled: false 추가
#
# 예제 (부동산 도메인):
# - name: "real_estate_inquiry"
#   display_name: "부동산 조회"
#   description: "부동산 매물 정보 조회"
#   keywords: ["아파트", "전세", "매매", "시세"]
#   confidence_threshold: 0.7
#   suggested_agents: ["search_team"]
#   priority: 1
